//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemirbasTakipOtomasyonu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OdaDemirbasAtama
    {
        public int Id { get; set; }
        public int OdaId { get; set; }
        public int DemirbasId { get; set; }
        public int AtananAdet { get; set; }
    
        public virtual Demirbas Demirbas { get; set; }
        public virtual Oda Oda { get; set; }
    }
}
